# Kliinisen lääketieteen perusteet (KLP) {#Kliinisen-laaketieteen-perusteet}

KLP on mielestäni C5:n huonoin kurssi, sillä kurssi koostuu sekalaisista eri erikoisaloilta napatuista paloista tietoa, jotka eivät muodosta järkevää kokonaisuutta. Todennäköisesti kurssin pääasiallinen tarkoitus on oppia potilaan tutkimisen perusteet, mutta nämä oppii muutenkin todella nopeasti paremmin sisätautien kurssilla, kun pääsee oikeasti tutkimaan potilaita. 

Statustamisen lisäksi kurssin opetusmateriaaleissa on runsaasti kaikenlaista muutakin tietoa, ja on vaikea päätellä, mitä kurssilla tulee oikeasti osata. 

Suosittelen ainakin opettelemaan statustamisen suhteen sydänäänet hyvin, sillä niiden osaamista ei painoteta dioissa tarpeeksi, vaikka ne ovat todella tärkeitä (ainakin yleisimpien läppävikojen suhteen). 

## Korteista huomio

Dioissa mainitaan usein ohimennen monia asioita, jonka takia tein alunperin todella monista asioista kurssin tageihin kortteja. Useimpia aiheita ei kuitenkaan tarvitse osata kovinkaan syvällisesti. Tämän takia tägäsin kortit uudestaan Luennot-tagin alle pienemmäksi paketiksi, jossa on pääasiassa vain luentodioissa opetettuja asioita eivätkä kortit mene kovin paljoa niitä syvemmälle. En osaa sanoa, riittääkö pelkkien diojen osaaminen vai vaaditaanko tentissä osaamista esim. potilaan tutkiminen-kirjasta tai jostain muualta. Tentit ovat kuitenkin yleisesti olleet todella helppoja (ainakin 2024), joten uskoisin pelkkien diojen riittävän. 

Kurssit-tagin alla on kuitenkin vielä ns. legacy-versio KLP:n kurssista, jossa on käytännössä kaikki kortit, jotka alunperin kuuluivat vuonna 2024 KLP:n kortteihin. Näitä voi kelata läpi halutessaan, mutta ne eivät ole ehkä järkevin kokonaisuus, sillä ei ole tarjolla fiksua opetusmateriaalia, joka kannattaisi lukaista ennen korttien läpikäymistä. 

## Workflow  

Jos luentoa ei ole tägätty luennot-tägin alle, niin siitä ei ole tehty kortteja ja olen arvioinut, että sen sisällöstä ei myöskään tarvita kortteja. Kannattaa kuitenkin nopeasti lukaista mainitsemattomien luentojen diat läpi ja miettiä tarvitseeko itse aiheista kortteja; näitä voi sitten ehdottaa AnkiCollabin kautta. 

Luennoilla mainitaan todella monta erilaista patologiaa, joten on vaikeaa haistaa, kuinka syvällisesti jokainen niistä pitää osata. Tärkeimmät asiat (eli suoraan/lähes suoraan dioissa opetetut) ovat tägätty "korkean annin"-tägin alle, joka kannattaa vähintään käydä läpi jokaisen luennon kohdalta. **Pääasiallinen workflow kurssilla onkin siis luentodiojen opiskeleminen -> korkean annin korttien läpikäyminen.** Oman maun mukaan voi sitten käydä läpi kohtalaisen ja matalan annin tägejä, mutta ne voivat olla hieman vaikeita, koska niiden materiaali on kerätty erilaisista lähteistä ja niitä edeltävä opiskelu voi olla hankalaa toteuttaa. 

Suosittelen, että jos jotkut sisätaudilliset aiheet kiinnostavat ja tuntuu, että kortit jättävät paljon kysymyksiä mieleen, niin voi käydä läpi sisätautien kurssin dioja ja sketchy-videoita, joiden jälkeen voi hypätä jo vähän etukäteen sisuskortteihin (tägätty C6::Sisätaudit-tägin alle). 
