# Ruotsin kielen suullinen taito 

Kurssi voi ruotsin taidostasi riippuen olla joko olla syksyn helpoin tai sitten vaikein. 
Vaikka ruotsi ei kiinnostaisi, niin kannattaa ymmärtää, että ruotsin osaaminen on todella hyödyllistä Turun seudulla. Minulla on jo lyhyellä urallani tullut vastaan lukuisia potilaita, jotka eivät puhu ollenkaan suomea, vaan ruotsi on ainoa yhteinen kielemme. Varsinkin jos pääsee Vaasaan hajautukseen, niin siellä lähes varmasti joutuu puhumaan ruotsia (minulla ei ollut Vaasassa sisusten hajautusviikolla yhtään suomenkielistä potilasta). Vaikka ruotsin taitoni ovat suhteellisen huonot, niin pienelläkin ruotsin taidolla tuntuu pärjäävän aika pitkälle.
 

## Suullinen tentti

Hyviä uutisia kurssin suhteen on se, että vaatimustaso suullisessa tentissä vaikuttaa olevan aika matala, ja jos vain osaa saada jotain järkevää suustaan ulos ruotsiksi, niin todennäköisesti pääsee tentistä läpi.

Tentti on paritentti, joten kannattaa valita pariksesi joku ruotsia hyvin osaava, sillä hän voi paikata huonon puhujan taitoja todella paljon (esim. auttaa ymmärtämään opettajan kysymyksiä ja pystyy ohjata keskustelua järkevästi, jos toinen alkaa empiä sanojensa kanssa). Aluksi harrastatte hieman småpratia kolmistaan opettajan kanssa, jonka jälkeen keskustelette hieman yhdestä syksyn potilastapaamisestanne. Sen jälkeen saatte vielä sattumanvaraisesti jonkun potilastapauksen keskusteltavaksi parisi kanssa. 

- Alkukeskustelun kysymyksiä, joita opettaja esitti minulle ja parilleni olivat mallia: Miten menee? Mitä olette tykänneet syksystä?  Mitä haluatte tehdä, sitten kun teistä tulee oikeita aikuisia? 

- Potilastapaamisen (syksyllä on yksi oikea potilastapaaminen, jossa suoritatte kunnon anamneesinoton) suhteen kysyttiin, että mikä oli mielestänne tärkein oppi ja mitä tykkäsitte potilastapaamisesta. 

- Potilastapaus valitaan sattumanvaraisesti paperipinosta. Lapulla lukee esim: Potilas juo paljon vettä, hänellä on pääkipuja ja vatsakipuja ja tekee yötyötä. Tästä tulee sitten keskustella kaverin kanssa, esim. mitä haluaisitte kysyä potilaalta, mitä tutkisitte, mikä on mahdolinen työdiagnoosi ja mahdollinen hoito. Samanlaisia harjoituksia on jo kurssin oppitunneillakin. 

## Sanastokoe 

Kurssista on vielä suullisen tentin lisäksi sanastokoe Examissa. Tämä kannattaa suorittaa ennen suullista tenttiä, sillä sanaston osaaminen on tärkeää suullisessakin osuudessa. 

Vaadittava sanasto löytyy Quizletista, mutta olen myös siirtänyt ne sieltä Rankiin (Ranki::Kurssit::C5::Muntlig), josta niiden spämmääminen Custom Study -sessioneilla on helppoa. Parempaa on tietysti kerrata sanoja pitkin kurssia, mutta tätä ei moni varmastikaan jaksa harrastaa, vaan pääasia on päästä kurssista läpi. 

- Suurin osa korteista on siirretty Quizletista sellaisessa muodossa, että kortista löytyy sekä suomesta->ruotsiksi -kortti että ruotsista->suomeksi -kortti. Jos haluat opetella vain toista puolta korteista, niin mene Ankin selaimeen tagin kohdalta ja jätä suspendatuksi se puolisko (reverse tai normal), jota et halua opiskella. Kortit saa reverse/normal järjestykseen, kun painaa selaimessa card type-kohtaa. 

Tentissä kysytään sanoja niin suomesta ruotsiksi kuin ruotsista suomeksi. Ruotsiksi kääntäessä tulee myös osata taivuttaa sanat. Tentissä on mukana myös lyhyitä lauseita. 